# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the podman-notebook directory and image
# Set the workflow name
name: JHub Podman Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/podman-notebook/ path
on:
  push:
    paths:
      - images/podman-notebook/**
    branches:
      - dev

env:
  BRANCH_NAME: ${{ github.ref_name }}

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  test-build-podman-nb:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: gh-arc-ccpp-images
    # Set the steps to take in order
    steps:
      - name: Install gh-cli
        run: |
            (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y
      # Checkout the github repo used to build the Container Image
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build podman notebook image
        run: |
          docker buildx create --use --driver=remote tcp://buildkit-buildkit-service.arc-systems:1234
          docker buildx build -f images/podman-notebook/Containerfile -t hub.k8s.ucar.edu/cislcloudpilot/ccpp-jhub-podman:${{ steps.date.outputs.date }} images/podman-notebook/.
      - name: Create pull request to merge dev in to main
        run: gh pr view ${{ env.BRANCH_NAME }} && gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create -B main -H ${{ env.BRANCH_NAME }}  --title 'Test build successful. Merge Podman notebook update from dev into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}