# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-image directory and image
# Set the workflow name
name: JHub Base Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-image/ path
on:
  push:
    paths:
      - images/base-image/**
    branches:
      - dev

env:
  BRANCH_NAME: ${{ github.ref_name }}

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  podman-build-base-image:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: self-hosted
    # Set the steps to take in order
    steps:
      # Checkout the github repo used to build the Container Image
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build base image
        run: |
          docker buildx create --use --driver=remote tcp://buildkit-buildkit-service.arc-systems:1234
          docker buildx build -f images/base-image/Containerfile -t hub.k8s.ucar.edu/cislcloudpilot/jhub-base:${{ steps.date.outputs.date }} images/base-image/.
      - name: Create pull request to merge dev in to main
        run: gh pr view ${{ env.BRANCH_NAME }} && gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create -B main -H ${{ env.BRANCH_NAME }} --title 'Test build successful. Merge JHub Base image update from dev into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}